name: "Bug Report"
description: Report a bug or unexpected behavior in Tubifarry
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to report an issue!
        Your feedback helps us make Tubifarry better for everyone.
  
  - type: input
    id: tubifarry-version
    attributes:
      label: Tubifarry Version
      description: |
        What version of Tubifarry are you running?
        Find this in: System → Plugin.

        Format must be: v1.8.1 (not "latest" or "newest")
      placeholder: v1.8.1
    validations:
      required: true

  - type: input
    id: lidarr-version
    attributes:
      label: Lidarr Version
      description: |
        What version of Lidarr are you using?
        Find this in: System → Status

        Format must be: v2.14.2 (not "latest")
      placeholder: v2.14.2
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Docker
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is and the specific feature that's not working.
      placeholder: |
        Example: "I was trying to... and then... The search function doesn't work as expected because..."
        
        Describe what you were trying to do and what went wrong:
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps so we can recreate the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected to see...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## How to Enable Trace Logging
        
        1. Go to Lidarr → Settings → General → Logging
        2. Set Log Level to **Trace** (not Debug, not Info)
        3. Click Save
        4. Reproduce your exact problem
        5. Go to System → Logs → Files tab
        6. Download the most recent log file
        7. Paste the relevant section below
        
        If your logs do not contain the word **`trace`**, your issue will be closed

  - type: textarea
    id: logs
    attributes:
      label: Trace Log Files
      description: |
        Paste only the relevant trace logs here. Do not delete the details tags.
      value: |
        <details>
        <summary>Logs</summary>

        ```plaintext
        Keep the plaintext markers intact and paste your logs in here...
        ```
        
        </details>
    validations:
      required: true

  - type: checkboxes
    id: log-checklist
    attributes:
      label: Log Checklist
      options:
        - label: I have enabled Trace logging in Lidarr before reproducing the issue
          required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: |
        <details>
        <summary>Screenshots</summary>
        
        <!-- Paste your screenshots here... -->
        
        </details>
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help us resolve the issue
    validations:
      required: false